repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace

# more checks can be enabled:
# https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.68.1
  hooks:
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
