name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Homebrew/actions/setup-homebrew@master
    - run: |
        make brew
        make lint
    # - uses: terraform-linters/setup-tflint@v1
    # - uses: pre-commit/action@v2.0.3
